sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start Creating an image with dockerfile"
  - docker build -t seungmoo.lee/docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true seungmoo.lee/docker-react-app npm run test -- --coverage

after_success:
  - echo "Test Success"

deploy:
  provider: elasticbeanstalk
  region: ap-northeast-2
  app: docker-react-app
  env: DockerReactApp-env
  bucket_name: elasticbeanstalk-ap-northeast-2-003232926877
  bucket_path: docker-react-app
  on:
    branch: master